//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSI : DbContext
    {
        public DBSI()
            : base("name=DBSI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Auction> Tbl_Auction { get; set; }
        public virtual DbSet<Tbl_BankNum> Tbl_BankNum { get; set; }
        public virtual DbSet<Tbl_Bills> Tbl_Bills { get; set; }
        public virtual DbSet<Tbl_Captcha> Tbl_Captcha { get; set; }
        public virtual DbSet<Tbl_Categories> Tbl_Categories { get; set; }
        public virtual DbSet<Tbl_Color> Tbl_Color { get; set; }
        public virtual DbSet<Tbl_Comment> Tbl_Comment { get; set; }
        public virtual DbSet<Tbl_ConfirmEmail> Tbl_ConfirmEmail { get; set; }
        public virtual DbSet<Tbl_ConfirmMobile> Tbl_ConfirmMobile { get; set; }
        public virtual DbSet<Tbl_Filter> Tbl_Filter { get; set; }
        public virtual DbSet<Tbl_Filter_Product> Tbl_Filter_Product { get; set; }
        public virtual DbSet<Tbl_Gallery> Tbl_Gallery { get; set; }
        public virtual DbSet<Tbl_GroupFilter> Tbl_GroupFilter { get; set; }
        public virtual DbSet<Tbl_GroupFilter_Categories> Tbl_GroupFilter_Categories { get; set; }
        public virtual DbSet<Tbl_KeyWord> Tbl_KeyWord { get; set; }
        public virtual DbSet<Tbl_Likes> Tbl_Likes { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_Message> Tbl_Message { get; set; }
        public virtual DbSet<Tbl_Payment> Tbl_Payment { get; set; }
        public virtual DbSet<Tbl_Products> Tbl_Products { get; set; }
        public virtual DbSet<Tbl_Sales> Tbl_Sales { get; set; }
        public virtual DbSet<Tbl_Setting> Tbl_Setting { get; set; }
        public virtual DbSet<Tbl_ShoppingCarts> Tbl_ShoppingCarts { get; set; }
        public virtual DbSet<Tbl_Slider> Tbl_Slider { get; set; }
        public virtual DbSet<Tbl_Status> Tbl_Status { get; set; }
        public virtual DbSet<Tbl_TempShoppingCart> Tbl_TempShoppingCart { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_Visit> Tbl_Visit { get; set; }
        public virtual DbSet<Tbl_Zarinpal> Tbl_Zarinpal { get; set; }
    }
}
