//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Message
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Read { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public int UserGet { get; set; }
        public Nullable<int> UserSend { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
        public virtual Tbl_User Tbl_User1 { get; set; }
    }
}
