//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TempShoppingCart
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string BankNo { get; set; }
        public bool Status { get; set; }
        public int ShoppingProductID { get; set; }
    
        public virtual Tbl_ShoppingCarts Tbl_ShoppingCarts { get; set; }
    }
}
