//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Color
    {
        public int ID { get; set; }
        public string CodeColor { get; set; }
        public int ProductID { get; set; }
        public string NameColor { get; set; }
        public Nullable<bool> DefaultColor { get; set; }
    
        public virtual Tbl_Products Tbl_Products { get; set; }
    }
}
