//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Comment()
        {
            this.Tbl_Comment1 = new HashSet<Tbl_Comment>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public string IP { get; set; }
        public bool Confirm_Comm { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comment> Tbl_Comment1 { get; set; }
        public virtual Tbl_Comment Tbl_Comment2 { get; set; }
        public virtual Tbl_Products Tbl_Products { get; set; }
    }
}
