//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BankNum
    {
        public int ID { get; set; }
        public string BankName { get; set; }
        public string CartNum { get; set; }
        public string BankNum { get; set; }
        public int UserID { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
