//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Menu
    {
        public string TitlePage { get; set; }
        public int Sort { get; set; }
        public bool Enable { get; set; }
        public string ContentPage { get; set; }
        public string Tag { get; set; }
        public string Description { get; set; }
    }
}
