//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sales
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public bool Payment { get; set; }
        public int Status { get; set; }
        public string GroupNo { get; set; }
        public int Count { get; set; }
        public string TransNo { get; set; }
        public string CodeRahgiri { get; set; }
        public string BankNo { get; set; }
    
        public virtual Tbl_Products Tbl_Products { get; set; }
        public virtual Tbl_Status Tbl_Status { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
