//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bills
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int Stock { get; set; }
        public int EndReceive { get; set; }
        public System.DateTime DateEndReceive { get; set; }
        public int AmountRequested { get; set; }
        public bool Requested { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
