//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sourceiran_MVC.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Categories()
        {
            this.Tbl_GroupFilter_Categories = new HashSet<Tbl_GroupFilter_Categories>();
            this.Tbl_Products = new HashSet<Tbl_Products>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int ParentID { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_GroupFilter_Categories> Tbl_GroupFilter_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Products> Tbl_Products { get; set; }
    }
}
